engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      ignore-undeclared: true
      dead-code-detection: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- test/
- vendor/
